### ISSUE TITLE
Need more detailed highlighting

### ISSUE THREAD

**Issue by xjArea** [s-h-a-d-o-w/NotepadPlusPlus-Remixed-Theme#4]
Good color themes, but I found the theme in JavaScript can't highlight the `new Object` and `new Array`, and it can't highligh the function like `parseInt()` or `parseFloat()`, if you use VSCode default theme like "Kimbie Dark", you can see more details.

I want to fixed it by myself, but now the highlight file is json, not xml ?, so it's hard for me, do you have any plan to update it again ? Now matter how, thank you for crated this theme and shared it. 🌹

**Comment by s-h-a-d-o-w** [comment]
I'm glad you're enjoying it on some level!

Certain things not being highlighted differently (or at all) is actually on purpose. I did this because I don't like "noisy" themes. I find it distracting when there are more than a few colors and font styles.

Highlighting global functions the same way as local functions would be an option I suppose but I prefer them to be different.

That said, the current theme format may be json but Sublime themes are clearly still supported, otherwise this theme wouldn't work.
So you could still simply fork & edit this and either install it [directly from your fork](https://stackoverflow.com/questions/50714638/install-extension-from-a-specific-repo-branch-on-github/54409592#54409592) or of course publish it if you think more people would enjoy your version. :)

**Comment by xjArea** [comment]
Oh, I see. I can try to refer to the "Kimbie Dark" theme to add some details by myself.
And thanks for your quick response.  😘❤

**Comment by s-h-a-d-o-w** [comment]
You're welcome! Have fun tweaking. :)
